// Generated by tool/sync_notes.dart from SCRIPT.md.
class LtPage {
  const LtPage({
    required this.route,
    required this.title,
    required this.seconds,
    required this.notes,
  });
  final String route;
  final String title;
  final int seconds;
  final String notes;
}

const ltPages = <LtPage>[
  LtPage(
    route: "/title",
    title: "そのFlutterコード、なぜ書いた？",
    seconds: 10,
    notes: "「そのFlutterコード、なぜ書いた？」。今日は、AIと開発する中で、自分が考えておきたいことを話します。",
  ),
  LtPage(
    route: "/about",
    title: "やくらん",
    seconds: 15,
    notes: "やくらんです。岡山.FlutterやFlutterKaigiで活動しています。今日は、だしゅまるの3DモデルをAIと作ってみた話から始めます。",
  ),
  LtPage(
    route: "/pace",
    title: "最近、進化が速すぎませんか",
    seconds: 25,
    notes: "最近、LLMの進化、すごいですよね。作る側もAIを使うようになって、フレームワークやパッケージの進化まで加速している感じがします。少し目を離すと、「え、もうそこまでできるの？」となる。Flutterの周りでも、そんな変化を感じています。",
  ),
  LtPage(
    route: "/flutter-scene",
    title: "半年前に紹介したFlutter Scene",
    seconds: 25,
    notes: "例えば、岡山.Flutterの初回で紹介したFlutter Scene。それから約半年で、当時の0.9.2系から、今回使ったのは0.23.0です。Webでも動き、サンプルも充実しています。Flutterで3Dを試す環境も、大きく変わりました。\n\n出典：[公式バージョン一覧](https://pub.dev/packages/flutter_scene/versions)、[0.23.0の公式README](https://pub.dev/packages/flutter_scene/versions/0.23.0)。前回紹介時期は本人提供の草案に基づきます。",
  ),
  LtPage(
    route: "/showcase",
    title: "これもFlutterなの？",
    seconds: 35,
    notes: "そしてAstraが登場して、モデルの3Dに対する理解も、一段深まったと感じます。SNSでも、「これ、本当にFlutterなの？」と思うグラフィックのアプリを、たくさん見かけるようになりました。\n\nこうした表現も、モデルの力を借りて、誰でも作れるようになってきたと感じています。自分でもやってみよう、と手が届く。例えば、こんなものです。\n\n出典：[Flutter Scene公式サイト](https://fscene.dev/)、[作者の紹介投稿（LinkedIn）](https://www.linkedin.com/posts/bderosier_flutter-dart-3d-activity-7485347941260496896-sOP7)。画像はFlutterの3D表現の参考例です。各作品がAstraで生成されたという説明にはしません。",
  ),
  LtPage(
    route: "/dashmaru",
    title: "モデルから、動くサンプルまで",
    seconds: 60,
    notes: "こちら、だしゅまるです。手を振ったり、歩いたり、ジャンプしたりできます。\n\nAstraへの一つの依頼を起点に、参考画像から3Dモデルを作り、それをFlutterで動かすサンプルまで、一気通貫で進められました。その後も動きや見た目を調整していますが、モデルもアプリも、まとめて頼めるんです。\n\n操作：モデルは導入中に事前読み込みされ、この画面で自動的に「手を振る」で登場します。デモ欄の「歩く」、「ジャンプ」を順に選びます。「待機」と一時停止も使えます。操作と動きを見せる間に約20秒を使います。\n\nだしゅまる：次のスライドで画面の右下へ小さく移り、以降も登場し続けます。\n\n表示できない場合：「参考画像からモデルを作り、Flutterで動かすサンプルまでLLMと進められました」と説明して次へ進みます。\n\n出典：[モデル・操作説明](../20260919_flutterkaigi_mini/README.md)、[改良と検証の記録](../20260919_flutterkaigi_mini/docs/verification.md)。使用モデルと依頼の経緯は本人提供の体験です。",
  ),
  LtPage(
    route: "/ideas",
    title: "アイデアを、動く形にしやすくなった",
    seconds: 20,
    notes: "小さな個人開発なら、「こんなのが欲しい」というアイデアから、動くものを試すところまでLLMと進められる。今回の体験で、アイデアを形にするまでのハードルが、ずいぶん下がったと感じています。\n\nだしゅまる：右下へ小さく移り、「待機」と「笑顔」。",
  ),
  LtPage(
    route: "/learning",
    title: "技術の勉強は、もういらない？",
    seconds: 20,
    notes: "ここまで作れるなら、業務の知識とアイデアがあれば十分なんでしょうか。私は、AIの提案を選び、確かめるときにも技術への理解を使うと思っています。\n\nだしゅまる：問いかけで少しの間ぐるぐる目になり、通常の表情に戻して一度まばたきします。",
  ),
  LtPage(
    route: "/priorities",
    title: "このアプリで、何を優先するか",
    seconds: 30,
    notes: "技術選定も、AIと相談できます。ただ、同じ検索アプリでも、短期間で試すのか、チームで長く育てるのかで、選びたい構成は変わります。\n\nこの条件では何が得られ、どんな負担を引き受けるのか。提案を自分たちの条件に当てはめるには、技術の特徴を知っておきたい。そのうえで、選んだ結果も確かめたいです。\n\nだしゅまる：「待機」。問いを考える間も、呼吸と小さな揺れを続けます。",
  ),
  LtPage(
    route: "/delegate",
    title: "細かいコードは、もっとAIに任せていい",
    seconds: 20,
    notes: "細かいコードの書き方は、もっとAIに任せていいと思っています。そのぶん、なぜこの構成なのか、そもそもなぜFlutterなのか。自分は、そうした選択の理由を考えることに時間を使いたいです。\n\nだしゅまる：右下で「待機」。呼吸と小さな揺れを続けます。",
  ),
  LtPage(
    route: "/decisions",
    title: "では、自分はどう選んだか",
    seconds: 20,
    notes: "ここからは、私自身の選択を紹介します。GitHubのリポジトリを検索するアプリのコーディング試験で、なぜそうしたかもメモに残しました。層を分ける理由と、層と機能のどちらを先に分けたかを見てみます。\n\nだしゅまる：「座る」。設計の説明中は、右下で座ったまま話を聞いています。\n\n出典：[本人の選定メモ](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/technical-decisions.md)。",
  ),
  LtPage(
    route: "/layers",
    title: "なぜ、責務を層で分けた？",
    seconds: 45,
    notes: "一つ目は、責務を層に分ける設計です。今回はオニオンアーキテクチャを採用し、業務ルールがUIや外部サービスの実装に依存しないようにしました。\n\nAIが速くコードを生成しても、自分が構造を把握して制御しやすくしたかったからです。層をまたがない変更なら、大きな組み替えを避けやすい、と考えました。コードが増えても、どこを変え、どんな境界を守るかが分かる構成を重視しています。\n\nだしゅまる：座ったまま、呼吸や小さな揺れを続けます。\n\n出典：[本人の選定メモ](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/technical-decisions.md#L46-L51)、[実際の依存関係](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/ARCHITECTURE.md#L5-L32)。",
  ),
  LtPage(
    route: "/organization",
    title: "なぜ、feature firstにしなかった？",
    seconds: 45,
    notes: "二つ目は、層と機能の、どちらを先に分けるかです。機能ごとにまとめるfeature firstに対して、今回は層を先に分けるlayer firstを選びました。\n\n業務では、機能をまたぐ処理や、責務が変わることが多いと考えているからです。層ごとに分けることで境界を意識しやすくし、責務が混ざるのを防ぎたい。\n\nただ、この検索アプリの要件ならfeature firstでも問題ない、とメモしています。今回は、今後の業務で使うことも意識した判断でした。\n\nだしゅまる：前のスライドから座った姿勢を保ちます。\n\n出典：[本人の選定メモ](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/technical-decisions.md#L59-L67)。両方とも層を設けられ、ここでは配置の優先順を比較しています。",
  ),
  LtPage(
    route: "/curiosity",
    title: "「使ってみたい」も、自分の理由",
    seconds: 40,
    notes: "理由は、いつも立派でなくていいと思います。「流行っているから」も、「使ってみたいから」も、きっかけになります。\n\nそこから、今回は実際の使い勝手を学びたい、まず個人開発で試せる範囲にする、と言葉を足してみる。Flutterを選ぶ理由にも、好きだから可能性を試したい、があっていい。\n\n目的に合っていて、引き受けることを分かっている。その状態で、自分の理由を話せるようになりたいです。\n\nここでの理由は聴き手に向けた例示です。特定の業務案件で本人がFlutterを選んだ理由としては扱いません。\n\nだしゅまる：座位から立ち上がり、一度ジャンプ。その後は「待機」と「笑顔」に切り替えます。",
  ),
  LtPage(
    route: "/sharing",
    title: "「なぜ？」を共有する",
    seconds: 35,
    notes: "「今回は、こういう理由で選びました」と話すと、他の人も自分の条件と比べられます。「その目的なら、こんな方法もあるよ」と教えてもらえるかもしれません。\n\n迷っているところも含めて話せば、そこから一緒に考えられます。自分の中に固定した正解を持つというより、今の理由を伝えて、知見や指摘をもらいながら更新していきたいです。\n\nだしゅまる：冒頭で一度「手を振る」。その後は「待機」に戻ります。",
  ),
  LtPage(
    route: "/why",
    title: "そのFlutterコード、なぜ書いた？",
    seconds: 25,
    notes: "だしゅまるも、AIと作れました。そのコードに、自分の選んだ理由も添えられるようになりたい。\n\n次にコードを書くとき、AIのコードを採用するとき、考えてみてください。\n\n**そのFlutterコード、なぜ書いた？**\n\nだしゅまる：通常の表情で「待機」。最後の問いの後に一拍置き、次へ進みます。",
  ),
  LtPage(
    route: "/thanks",
    title: "ご清聴ありがとうございました",
    seconds: 10,
    notes: "ご清聴ありがとうございました。\n\nだしゅまる：「手を振る」と「笑顔」。一礼したあとも、この画面でバイバイを続けます。",
  ),
];
