// Generated by tool/sync_notes.dart from SCRIPT.md.
import 'speaker_notes.dart';

class LtPage {
  const LtPage({
    required this.route,
    required this.title,
    required this.seconds,
    required this.notes,
  });
  final String route;
  final String title;
  final int seconds;
  final String notes;
}

const ltPages = <LtPage>[
  LtPage(
    route: "/title",
    title: "そのFlutterコード、なぜ書いた？",
    seconds: 10,
    notes: SpeakerNotes.title,
  ),
  LtPage(
    route: "/about",
    title: "やくらん",
    seconds: 20,
    notes: SpeakerNotes.about,
  ),
  LtPage(
    route: "/pace",
    title: "最近、進化が速すぎませんか",
    seconds: 20,
    notes: SpeakerNotes.pace,
  ),
  LtPage(
    route: "/flutter-scene",
    title: "半年前に紹介したFlutter Scene",
    seconds: 25,
    notes: SpeakerNotes.flutterScene,
  ),
  LtPage(
    route: "/showcase",
    title: "これもFlutterなの？",
    seconds: 25,
    notes: SpeakerNotes.showcase,
  ),
  LtPage(
    route: "/dashmaru",
    title: "3Dの知識がなくてもモデル作成からサンプルまで",
    seconds: 45,
    notes: SpeakerNotes.dashmaru,
  ),
  LtPage(
    route: "/ideas",
    title: "アイデアがそのまま動くものに",
    seconds: 20,
    notes: SpeakerNotes.ideas,
  ),
  LtPage(
    route: "/learning",
    title: "技術の勉強は、もういらない？",
    seconds: 20,
    notes: SpeakerNotes.learning,
  ),
  LtPage(
    route: "/priorities",
    title: "アプリの組み立て方を学ぶ",
    seconds: 40,
    notes: SpeakerNotes.priorities,
  ),
  LtPage(
    route: "/decisions",
    title: "使い方と一緒に、使いどころを学ぶ",
    seconds: 25,
    notes: SpeakerNotes.decisions,
  ),
  LtPage(
    route: "/layers",
    title: "作りながら、「なぜ？」を考える",
    seconds: 25,
    notes: SpeakerNotes.layers,
  ),
  LtPage(
    route: "/why",
    title: "そのFlutterコード、なぜ書いた？",
    seconds: 20,
    notes: SpeakerNotes.why,
  ),
  LtPage(
    route: "/thanks",
    title: "ご清聴ありがとうございました",
    seconds: 5,
    notes: SpeakerNotes.thanks,
  ),
];
