// Generated by tool/sync_notes.dart from SCRIPT.md.
class LtPage {
  const LtPage({
    required this.route,
    required this.title,
    required this.seconds,
    required this.notes,
  });
  final String route;
  final String title;
  final int seconds;
  final String notes;
}

const ltPages = <LtPage>[
  LtPage(
    route: "/title",
    title: "そのFlutterコード、なぜ書いた？",
    seconds: 10,
    notes: "「そのFlutterコード、なぜ書いた？」。今日は、コードと一緒に、自分が選んだ理由も持っておきたいという話です。",
  ),
  LtPage(
    route: "/about",
    title: "やくらん",
    seconds: 15,
    notes: "やくらんです。岡山に住んでいて、Flutter、Dart、Webを使っています。趣味はスマブラSPと個人開発です。Xはこちらです。今日は、だしゅまるをAIと作った話から始めます。",
  ),
  LtPage(
    route: "/pace",
    title: "最近、進化が速すぎませんか",
    seconds: 25,
    notes: "最近、LLMの進化、すごいですよね。作る側もAIを使うようになって、フレームワークやパッケージの進化まで加速している感じがします。少し目を離すと「え、もうそこまでできるの？」となる。Flutterの周りでも、そんな変化を感じています。",
  ),
  LtPage(
    route: "/flutter-scene",
    title: "半年前に紹介したFlutter Scene",
    seconds: 25,
    notes: "例えば、2026年3月の岡山.Flutterで紹介したFlutter Scene。それから約半年で、当時の0.9.2系から、今回使ったのは0.23.0です。Webでも動き、サンプルも充実しています。Flutterで3Dを試す環境も、大きく変わりました。\n\n出典：[公式バージョン一覧](https://pub.dev/packages/flutter_scene/versions)、[0.23.0の公式README](https://pub.dev/packages/flutter_scene/versions/0.23.0)。2026/03という紹介時期は本人提供の情報に基づきます。",
  ),
  LtPage(
    route: "/showcase",
    title: "これもFlutterなの？",
    seconds: 35,
    notes: "そしてAstraが登場して、モデルの3Dに対する理解も、一段深まったと感じます。SNSでも、「これ、本当にFlutterなの？」と思うグラフィックのアプリを、たくさん見かけるようになりました。\n\nこうした表現も、モデルの力を借りて、誰でも作れるようになってきたと感じています。自分でもやってみよう、と手が届く。例えば、こんなものです。\n\n操作：PBR・ライティングのサムネイルを押して短く再生します。読み上げに重ねて見せ、ページを進めると動画を停止します。\n\n出典：[Flutter Scene公式サイト](https://fscene.dev/)、[作者の紹介投稿（LinkedIn）](https://www.linkedin.com/posts/bderosier_flutter-dart-3d-activity-7485347941260496896-sOP7)。動画はFlutterの3D表現の参考例です。各作品がAstraで生成されたという説明にはしません。",
  ),
  LtPage(
    route: "/dashmaru",
    title: "知識がなくてもモデル作成からサンプルまで",
    seconds: 60,
    notes: "こちら、だしゅまるです。手を振ったり、走ったり、ぶんぶんしたり、ジャンプしたりできます。\n\nAstraへの一つの依頼を起点に、参考画像から3Dモデルを作り、それをFlutterで動かすサンプルまで、一気通貫で進められました。その後も動きや見た目を調整していますが、モデルもアプリも、まとめて頼めるんです。\n\n操作：モデルは導入中に事前読み込みされ、この画面で自動的に「手を振る」で登場します。デモ欄の「走る」「ぶんぶん」「ジャンプ」を順に選びます。「手を振る」に戻したり、再生・一時停止したりもできます。操作と動きを見せる間に約20秒を使います。\n\nだしゅまる：次のスライドで画面の右下へ小さく移り、以降も登場し続けます。\n\n表示できない場合：「参考画像からモデルを作り、Flutterで動かすサンプルまでLLMと進められました」と説明して次へ進みます。\n\n出典：[モデル・操作説明](../20260919_flutterkaigi_mini/README.md)、[改良と検証の記録](../20260919_flutterkaigi_mini/docs/verification.md)。使用モデルと依頼の経緯は本人提供の体験です。",
  ),
  LtPage(
    route: "/ideas",
    title: "アイデアがそのまま動くものに",
    seconds: 20,
    notes: "小さな個人開発なら、「こんなのが欲しい」というアイデアから、動くものを試すところまでLLMと進められる。今回の体験で、アイデアを形にするまでのハードルが、ずいぶん下がったと感じています。\n\nだしゅまる：右下へ小さく移り、「喜ぶ」と「笑顔」を組み合わせてループします。",
  ),
  LtPage(
    route: "/learning",
    title: "技術の勉強は、もういらない？",
    seconds: 20,
    notes: "ここまで作れるなら、業務の知識とアイデアがあれば十分なんでしょうか。私は、AIの提案を選び、確かめるときにも技術への理解を使うと思っています。\n\nだしゅまる：「ぶんぶん」と「踏ん張る」の表情を組み合わせてループします。",
  ),
  LtPage(
    route: "/priorities",
    title: "このアプリで「なに」を優先させるか？",
    seconds: 30,
    notes: "技術選定も、AIと相談できます。ただ、同じ検索アプリでも、短期間で試すのか、チームで長く育てるのかで、選びたい構成は変わります。\n\nこの条件では何が得られ、どんな負担を引き受けるのか。提案を自分たちの条件に当てはめるには、技術の特徴を知っておきたい。そのうえで、選んだ結果も確かめたいです。\n\nだしゅまる：「座る」と「ぐるぐる目」を組み合わせてループします。前の場面でぶんぶんしすぎて疲れたように見せます。",
  ),
  LtPage(
    route: "/delegate",
    title: "「なぜ」を考える時間を増やしたい",
    seconds: 20,
    notes: "細かいコードの書き方は、もっとAIに任せていいと思っています。そのぶん、なぜこの構成を選ぶのか。自分たちの条件で何がうれしくて、どんな手間が増えるのか。そこを考える時間を増やしたいです。\n\nだしゅまる：ぐるぐる目から通常の表情へ戻り、座ったまま右下で話を聞きます。",
  ),
  LtPage(
    route: "/decisions",
    title: "よく聞く設計の話を、3つの問いに",
    seconds: 20,
    notes: "例えば、よく話題になるこの3つ。配置の話、画面の責務の話、依存関係の話と、見ているところが違います。それぞれ、何を解決したくて選ぶのか。自分の実例も交えて考えてみます。\n\nだしゅまる：「座る」。設計の説明中は、右下で座ったまま話を聞きます。\n\nこの3つは排他的な選択肢ではありません。配置・画面の責務・依存の方向という異なる観点で、組み合わせて考えられる話題として扱います。",
  ),
  LtPage(
    route: "/layers",
    title: "feature first / layer firstを選ぶ理由",
    seconds: 45,
    notes: "feature firstは機能ごと、layer firstは責務の層ごとに先にまとめる配置です。自分は、業務では機能をまたぐ処理や責務の変化が多いと考えて、layer firstを選びました。人にもAIにも、置き場所と境界を意識してほしかったからです。\n\n一方で、一つの機能の変更が複数の層に広がると、追う場所は増えます。feature firstでも層は分けられますし、どちらを先に見たいかはプロジェクト次第だと思います。\n\nだしゅまる：座ったまま、呼吸や小さな揺れを続けます。\n\n出典：[本人の選定メモ](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/technical-decisions.md#L53-L67)。機能横断・責務の変化を意識してlayer firstを選んだ理由は本人の記録です。両方とも層を設けられ、ここでは配置の優先順を比較しています。得られる見通しと変更時に追う場所の説明は、記録をもとにした発表用の整理です。",
  ),
  LtPage(
    route: "/organization",
    title: "MVVMで、何を分けたい？",
    seconds: 45,
    notes: "MVVMなら、表示する側と、画面の状態や操作を扱う側を分けます。画面の判断が複雑で、Widgetとは別にテストしたいなら、その分離には意味があります。ただ、クラスを増やすなら役割も決めたい。\n\n自分の実装では、アプリ状態をApplication Providerに集約し、画面専用のViewModelは追加していません。新しく置くなら、何をそこへ任せるのか。既存の状態と責務が重ならないかまで考えたいです。\n\nだしゅまる：前のスライドから座った姿勢を保ちます。\n\n出典：[Flutter公式のアーキテクチャガイド](https://docs.flutter.dev/app-architecture/guide#ui-layer)、[実際のアーキテクチャ](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/ARCHITECTURE.md#L132-L137)。画面専用のViewModelを置かずApplication Providerを状態の基準とする点は実装方針に記載されています。MVVMへの賛否や不採用の動機は本人の選定メモにないため断定せず、追加する責務と手間を考える問いとして構成しています。ProviderとViewModelを排他的な技術として比較しません。",
  ),
  LtPage(
    route: "/curiosity",
    title: "Clean Architectureで、何を守りたい？",
    seconds: 40,
    notes: "Clean Architectureでは、業務ルールが外側の実装に依存しないようにします。自分が採用したのは、近い考え方のオニオンアーキテクチャです。AIが速く生成しても、どこを変えてよいか把握しやすくしたかった。\n\n一方、境界やデータ変換を保守する手間は増えます。守りたいものに、その手間が見合うか。そこまで理由にして、他の人にも話せるようになりたいです。\n\nだしゅまる：座位から立ち上がり、「待機」で呼吸や小さな揺れを続けます。\n\n出典：[Clean Architectureの原典](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)、[本人の選定メモ](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/technical-decisions.md#L36-L51)、[実際の依存関係](https://github.com/yakitama5/material_github_searcher/blob/57d9662dcdbfe1a93e6bb0b4706bfa778db8ba05/docs/ARCHITECTURE.md#L5-L32)。本人が採用した名称はオニオンアーキテクチャです。Clean Architectureと同一とはせず、業務ルールと外部実装を分ける近い考え方として説明します。構造を把握して制御したいという理由は本人の記録、手間との釣り合いは発表用の問いです。",
  ),
  LtPage(
    route: "/sharing",
    title: "「なぜ？」を共有する",
    seconds: 35,
    notes: "「今回は、こういう理由で選びました」と話すと、他の人も自分の条件と比べられます。「その目的なら、こんな方法もあるよ」と教えてもらえるかもしれません。\n\n「使ってみたいから」も、迷っているところも含めて話せば、そこから一緒に考えられます。今の理由を伝えて、知見や指摘をもらいながら更新していきたいです。\n\nだしゅまる：冒頭で一度「手を振る」。その後は「待機」に戻ります。",
  ),
  LtPage(
    route: "/why",
    title: "そのFlutterコード、なぜ書いた？",
    seconds: 25,
    notes: "だしゅまるも、AIと作れました。そのコードに、自分の選んだ理由も添えられるようになりたい。\n\n次にコードを書くとき、AIのコードを採用するとき、考えてみてください。\n\n**そのFlutterコード、なぜ書いた？**\n\nだしゅまる：通常の表情で「待機」。最後の問いの後に一拍置き、次へ進みます。",
  ),
  LtPage(
    route: "/thanks",
    title: "ご清聴ありがとうございました",
    seconds: 10,
    notes: "ご清聴ありがとうございました。\n\nだしゅまる：「手を振る」と「笑顔」。一礼したあとも、この画面でバイバイを続けます。",
  ),
];
