import 'dart:convert';
import 'dart:io';

/// Run from this slide package after editing SCRIPT.md.
void main(List<String> arguments) {
  const routes = [
    '/title',
    '/about',
    '/pace',
    '/flutter-scene',
    '/showcase',
    '/dashmaru',
    '/ideas',
    '/learning',
    '/priorities',
    '/delegate',
    '/decisions',
    '/layers',
    '/organization',
    '/curiosity',
    '/sharing',
    '/why',
    '/thanks',
  ];
  final script = File('SCRIPT.md').readAsStringSync();
  final sections = RegExp(
    r'^## \d{2} (.+)\n([\s\S]*?)(?=^## |$(?![\s\S]))',
    multiLine: true,
  ).allMatches(script).toList();
  if (sections.length != routes.length) {
    throw StateError('Expected 17 scenes in SCRIPT.md.');
  }
  String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
  final output = StringBuffer(
    '''// Generated by tool/sync_notes.dart from SCRIPT.md.
class LtPage {
  const LtPage({required this.route, required this.title, required this.seconds, required this.notes});
  final String route;
  final String title;
  final int seconds;
  final String notes;
}

const ltPages = <LtPage>[
''',
  );
  var total = 0;
  for (var index = 0; index < sections.length; index++) {
    final section = sections[index];
    final body = section.group(2)!;
    final seconds = int.parse(RegExp(r'（(\d+)秒）').firstMatch(body)!.group(1)!);
    final notes = body.split('**話す**').last.trim();
    if (!body.contains('**話す**') || notes.isEmpty) {
      throw StateError('Missing speaker notes.');
    }
    total += seconds;
    output.writeln(
      'LtPage(route: ${literal(routes[index])}, title: ${literal(section.group(1)!)}, seconds: $seconds, notes: ${literal(notes)}),',
    );
  }
  output.writeln('];');
  File('lib/pages.dart').writeAsStringSync(output.toString());
  final formatted = Process.runSync(Platform.resolvedExecutable, [
    'format',
    'lib/pages.dart',
  ]);
  if (formatted.exitCode != 0) throw StateError('${formatted.stderr}');
  stdout.writeln('Synced ${sections.length} scenes, $total seconds.');
}
